# Generated by Django 4.0.6 on 2022-07-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_state_shippingaddress_county_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='county',
            new_name='state',
        ),
    ]
