# Generated by Django 4.0.6 on 2022-07-26 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_rename_state_shippingaddress_county_and_more'),
    ]

    operations = [
    ]
